### ISSUE TITLE
clarify license /usage

### ISSUE THREAD

**Issue by psifertex** [riverloopsec/hashashin#3]
Might be nice to clarify on the readme that a headless license works, but so does a regular commercial license since you can use the full version with UI in a headless mode just as well as a dedicated headless.

Of course, if you're running the docker instance at the same time as another copy of binaryninja you should be purchasing an additional license, but that's really only necessary for lots of bulk processing (which is the purpose of a headless license which is actually cheaper than a regular license).

Happy to make a suggested text change via PR if you prefer that as well.

**Comment by rmspeers** [comment]
Hi, yes Jordan please submit a PR to clarify!
